/**:
  ros__parameters:
    # require_game_running: false # 程序内默认硬编码为True

    # referee topics
    referee_robot_status_topic: "referee/robot_status"
    referee_game_status_topic:  "referee/game_status"
    referee_rfid_status_topic:  "referee/rfid_status"
    
    # nav2 goal_pose
    goal_pose_topic: "goal_pose"
    map_frame_id: "map"
    base_frame_id: "map"

    # chassis
    chassis_mode_topic: "chassis_mode"
    
    # goals（来自 XML）
    supply_x: 0.0
    supply_y: 0.0

    default_x: 1.0   #4.65
    default_y: -1.0  #-3.5

    # thresholds（来自 XML）
    hp_survival_enter: 120
    hp_survival_exit: 300
    heat_supply_done: 100
    hp_supply_done: 399
    default_arrive_xy_tol: 0.30
    default_spin_keep_xy_tol: 0.80
    combat_max_distance: 8.0
    combat_cooldown_sec: 3.0

    goal_hz: 10.0
    tick_hz: 20.0

    start_delay_sec: 3.0
