/**:
  ros__parameters:
    # require_game_running: false # 程序内默认硬编码为True

    # referee topics
    referee_robot_status_topic: "referee/robot_status"
    referee_game_status_topic:  "referee/game_status"
    referee_rfid_status_topic:  "referee/rfid_status"
    
    # nav2 goal_pose
    map_frame_id: "map"
    base_frame_id: "map"

    # chassis
    chassis_mode_topic: "chassis_mode"
    
    # goals（来自 XML）
    supply_x: 0.0
    supply_y: 0.0

    default_x: 1.0   #4.65
    default_y: -1.0  #-3.5

    hp_heal: 120
    hp_attack: 300
    tol_radius_min: 0.30 # 是否认为其接近目标点并切换为小陀螺模式的容许半径
    tol_radius_max: 0.80 # 是否维持小陀螺的容许半径

    goal_hz: 10.0
    tick_hz: 20.0

    start_delay_sec: 3.0
