cd ~/nav2_ws
source ./install/setup.bash
cd ~/nav2_ws/ros2bag_nav
ros2 bag record /Laser_map \
    /aft_mapped_to_init \
    /bond \
    /cloud_clearing \
    /cloud_effected \
    /cloud_registered \
    /cloud_registered_body \
    /cmd_gimbal_joint \
    /cmd_shoot \
    /cmd_spin \
    /cmd_vel \
    /cmd_vel_nav2_result \
    /diagnostics \
    /initialpose \
    /joint_states \
    /joy \
    /joy/set_feedback \
    /lidar_odometry \
    /livox/imu \
    /livox/lidar \
    /livox/lidar/pointcloud \
    /local_plan \
    /map \
    /map_clearing \
    /map_metadata \
    /map_saver/transition_event \
    /map_updates \
    /obstacle_scan \
    /odometry \
    /parameter_events \
    /path \
    /pose \
    /registered_scan \
    /robot_description \
    /rosout \
    /slam_toolbox/feedback \
    /slam_toolbox/graph_visualization \
    /slam_toolbox/scan_visualization \
    /slam_toolbox/update \
    /terrain_map \
    /terrain_map_ext \
    /tf \
    /tf_static
